### ISSUE TITLE
Branje .xls datoteke seznama aktivnih zobozdravnikov

### ISSUE THREAD

**Issue by Glusk** [Glusk/sveder#3]
Dodaj funkcionalnost za branje `.xls` datotek z seznamom aktivnih zobozdravnikov. Iz datotek preberi naslednja polja:

- Šifra izvajalca
- Šifra zdravnika
- Doseganje povprečja

**Comment by Glusk2** [comment]
Delno bo treba popraviti tudi Checkstyle (npr. za dovoljevanje daljših linkov v Doc komentarjih).

**Comment by Glusk** [comment]
Število vrstic na začetku lista, ki niso podatki (oznake stolpcev, podatki o datumu objave, ...), ni fiksno med mesečnimi objavami preglednic zavoda. Popravi logiko.
